rubies:
  - "ree-1.8.7-2012.02"
  - "ruby-1.9.2-p320"
  - "ruby-1.9.3-p484"
  - "ruby-2.0.0-p353"
  - "jruby-1.7.10"
  - "rubinius-2.2.3"
rubygems:
  ree-1.8.7-2012.02: "1.4.1"
  1.9.2-p320: "1.5.2"
  1.9.3-p484: "1.8.28"
  2.0.0-p353: "2.2.1"
  2.1.0: "2.2.1"
  jruby-1.7.10: "2.2.1"
  rbx-2.2.3: "2.2.1"
gems:
  ruby-1.9.2-p320:
  - name: bundler
    version: 1.3.5
  - name: rake
    version: 0.8.7
  ruby-1.9.3-p484:
  - name: bundler
    version: 1.5.2
  - name: rake
    version: 10.1.0
  ruby-2.0.0-p353:
  - name: bundler
    version: 1.5.2
  - name: rake
    version: 10.1.0
  ruby-2.1.0:
  - name: bundler
    version: 1.5.2
  - name: rake
    version: 10.1.1
  jruby-1.7.10:
  - name: bundler
    version: 1.5.2
  - name: rake
    version: 10.1.0
  rbx-2.2.3:
  - name: bundler
    version: 1.5.2
  - name: rake
    version: 10.1.0
  - name: rubysl
    version: 2.0.15
  ree-1.8.7-2012.02:
  - name: bundler
    version: 1.0.10
  - name: rake
    version: 0.8.7
base_box: http://rubies.shellycloud.com/boxes/debian_8_jessie_64bit.box
